<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>adoc</string>
		<string>asciidoc</string>
	</array>
	<key>name</key>
	<string>AsciiDoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\..*</string>
			<key>name</key>
			<string>markup.heading.title.asciidoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\* </string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>markup.list.unnumbered.asciidoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\d+\.  .*</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>markup.list.numbered.asciidoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^.+::</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>markup.list.variable.asciidoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^&lt;\d+&gt;.*$</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>markup.list.numbered.callout.asciidoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^NOTE:.*</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>markup.note.asciidoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^WARNING:.*</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>markup.warning.asciidoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\|===$</string>
			<key>end</key>
			<string>^\|===$</string>
			<key>name</key>
			<string>markup.list.table.asciidoc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(```\w*|----+)$</string>
			<key>end</key>
			<string>^(```|----+)$</string>
			<key>name</key>
			<string>markup.raw.asciidoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;\d+&gt;</string>
					<key>name</key>
					<string>markup.list.numbered.callout.asciidoc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^=+$</string>
			<key>name</key>
			<string>markup.heading.0.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-+$</string>
			<key>name</key>
			<string>markup.heading.1.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^~+$</string>
			<key>name</key>
			<string>markup.heading.2.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\^+$</string>
			<key>name</key>
			<string>markup.heading.3.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\++$</string>
			<key>name</key>
			<string>markup.heading.4.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[=#]{1}.*$</string>
			<key>name</key>
			<string>markup.heading.0.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[=#]{2}.*$</string>
			<key>name</key>
			<string>markup.heading.1.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[=#]{3}.*$</string>
			<key>name</key>
			<string>markup.heading.2.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[=#]{4}.*$</string>
			<key>name</key>
			<string>markup.heading.3.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[=#]{5}.*$</string>
			<key>name</key>
			<string>markup.heading.4.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^image::.*$</string>
			<key>name</key>
			<string>variable.other.image.block.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^.+&lt;.+@.+&gt;$</string>
			<key>name</key>
			<string>variable.other.author.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^:.*:.*$</string>
			<key>name</key>
			<string>variable.other.asciidoc</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>bold</key>
				<dict>
					<key>match</key>
					<string>\*[^\*]+\*</string>
					<key>name</key>
					<string>markup.bold.asciidoc</string>
				</dict>
				<key>comment</key>
				<dict>
					<key>match</key>
					<string>//.*</string>
					<key>name</key>
					<string>comment.line.double-slash.asciidoc</string>
				</dict>
				<key>italic</key>
				<dict>
					<key>match</key>
					<string>_[^_]+_</string>
					<key>name</key>
					<string>markup.italic.asciidoc</string>
				</dict>
				<key>link</key>
				<dict>
					<key>match</key>
					<string>&lt;&lt;[^&gt;]+&gt;&gt;</string>
					<key>name</key>
					<string>markup.underline.link.asciidoc</string>
				</dict>
				<key>raw</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.asciidoc</string>
						</dict>
						<key>2</key>
						<dict/>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.asciidoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(`)([^`]+)(`)</string>
					<key>name</key>
					<string>markup.raw.asciidoc</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.asciidoc</string>
	<key>uuid</key>
	<string>2610581D-81E3-4252-ADE5-B8C6F7019353</string>
</dict>
</plist>
